version: "3.1"
services:
    webserver:
        image: nginx:alpine
        container_name: zandstra-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

    php-fpm:
        build: docker/php-fpm
        container_name: zandstra-php-fpm
        working_dir: /application
        ports:
            - "9000:9000"
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini